### ISSUE TITLE
Removing all text doesn't disable that text response

### ISSUE THREAD

**Issue by SirVG** [dDeepLb/BC-Responsive#1]
While I know there's an option under Settings -> Enable Character Talk to disable text responses, it would be nice that if you completely remove all the text listing under a certain entry (tickle or boop for example) that it doesn't just give a generic/default response, but instead gives no response. It would be nice to be able to give some auto-responses to certain things, but not others.

Hopefully that can be a future feature of the add-on.

Thanks!

**Comment by dDeepLb** [comment]
It shouldn't respond with default message, I'll work on it

**Comment by dDeepLb** [comment]
@SirVG FIXED
